# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='予約日時')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='企業名')),
                ('store_name', models.CharField(max_length=255, verbose_name='店舗名')),
                ('thumbnail', models.ImageField(upload_to='images/', verbose_name='ロゴ')),
                ('title', models.CharField(max_length=255, verbose_name='タイトルタグ')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company', verbose_name='企業'),
        ),
    ]
